import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link } from "wouter";
import { Bell, BellRing, ClipboardList, PackageCheck, Pencil, Printer, RefreshCw, Truck, WalletCards } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { toast } from "sonner";

type OrderStatus = "pending" | "confirmed" | "production" | "preparing" | "shipping" | "delivered" | "cancelled";
type Order = { id:number; orderNumber:string; status:OrderStatus; fabricName?:string|null; fabricColor?:string|null; profileColor?:string|null; mountType?:string|null; caseType?:string|null; width?:string|number|null; height?:string|number|null; quantity?:number|null; totalPrice:string|number; customerName?:string|null; customerPhone?:string|null; customerAddress?:string|null; customerCity?:string|null; customerNote?:string|null; createdAt:string|Date };
const statusLabels: Record<OrderStatus,string> = { pending:"Bekliyor", confirmed:"Onaylandı", production:"İmalatta", preparing:"Hazırlanıyor", shipping:"Kargoda", delivered:"Teslim Edildi", cancelled:"İptal Edildi" };
const statusOptions = Object.entries(statusLabels) as Array<[OrderStatus,string]>;
const LAST_ORDER_KEY = "rgnfix-admin-last-order-id";
const money = (value:string|number) => new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:2}).format(Number(value||0));
const date = (value:string|Date) => new Intl.DateTimeFormat("tr-TR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));
const esc = (value:unknown) => String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");

function printOrder(order:Order){
  const popup=window.open("","_blank","width=620,height=900"); if(!popup) return void toast.error("Yazdırma penceresi engellendi.");
  popup.document.write(`<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>Sipariş ${esc(order.orderNumber)}</title><style>@page{size:A5 portrait;margin:9mm}body{font-family:Arial;color:#123;font-size:11px}.sheet{border:2px solid #123;padding:9mm}.head{display:flex;justify-content:space-between;border-bottom:2px solid #123;padding-bottom:8mm}.brand{font-size:26px;font-weight:900}.section{margin-top:7mm}.row{display:flex;border-bottom:1px dotted #ccc;padding:2mm 0}.label{width:35mm;color:#667}.value{font-weight:700}.total{margin-top:8mm;background:#eef7f7;padding:5mm;display:flex;justify-content:space-between;font-size:16px}</style></head><body onload="window.print()"><div class="sheet"><div class="head"><div class="brand">RGNFIX</div><div><b>#${esc(order.orderNumber)}</b><br>${esc(date(order.createdAt))}</div></div><div class="section"><div class="row"><div class="label">Müşteri</div><div class="value">${esc(order.customerName)}</div></div><div class="row"><div class="label">Telefon</div><div class="value">${esc(order.customerPhone)}</div></div><div class="row"><div class="label">Adres</div><div class="value">${esc(order.customerCity)} ${esc(order.customerAddress)}</div></div></div><div class="section"><div class="row"><div class="label">Ürün</div><div class="value">${esc(order.fabricName)} / ${esc(order.fabricColor)}</div></div><div class="row"><div class="label">Profil / Montaj</div><div class="value">${esc(order.profileColor)} / ${esc(order.mountType)}</div></div><div class="row"><div class="label">Ölçü</div><div class="value">${esc(order.width)} × ${esc(order.height)} cm · ${esc(order.quantity)} adet</div></div></div><div class="section"><b>Not:</b><p>${esc(order.customerNote)}</p></div><div class="total"><span>TOPLAM</span><b>${esc(money(order.totalPrice))}</b></div></div></body></html>`); popup.document.close();
}

export default function AdminPanel(){
  const {user,loading:authLoading}=useAuth({redirectOnUnauthenticated:true,redirectPath:"/giris"});
  const [orders,setOrders]=useState<Order[]>([]); const ordersRef=useRef<Order[]>([]); const audioRef=useRef<AudioContext|null>(null);
  const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [demoMode,setDemoMode]=useState(false); const [updatingId,setUpdatingId]=useState<number|null>(null);
  const [permission,setPermission]=useState<NotificationPermission>(typeof Notification==="undefined"?"denied":Notification.permission); const firstLoad=useRef(true);

  const playSound=useCallback(()=>{try{const C=window.AudioContext||(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!C)return;const ctx=audioRef.current||new C();audioRef.current=ctx;void ctx.resume();const now=ctx.currentTime;[740,988,1318,1760].forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=f;o.type="sine";g.gain.setValueAtTime(.0001,now+i*.14);g.gain.exponentialRampToValueAtTime(.28,now+i*.14+.02);g.gain.exponentialRampToValueAtTime(.0001,now+i*.14+.12);o.connect(g).connect(ctx.destination);o.start(now+i*.14);o.stop(now+i*.14+.14)});}catch(e){console.warn(e)}},[]);
  const notify=useCallback((items:Order[])=>{if(!items.length)return;playSound();const newest=items[0];toast.success(`Yeni sipariş: #${newest.orderNumber}`);if(typeof Notification!=="undefined"&&Notification.permission==="granted")new Notification("RGNFIX Yeni Sipariş",{body:`#${newest.orderNumber} · ${newest.customerName||"Müşteri"} · ${money(newest.totalPrice)}`,icon:"/favicon.ico"});},[playSound]);
  const loadOrders=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const r=await fetch("/api/admin/orders",{credentials:"include"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Siparişler yüklenemedi.");const next=d.orders||[];const max=next.reduce((m: number,o:Order)=>Math.max(m,Number(o.id)),0);const stored=Number(localStorage.getItem(LAST_ORDER_KEY)||"0");const current=ordersRef.current.reduce((m,o)=>Math.max(m,Number(o.id)),0);if(!firstLoad.current||stored>0)notify(next.filter((o:Order)=>Number(o.id)>Math.max(stored,current)));if(max>0)localStorage.setItem(LAST_ORDER_KEY,String(max));firstLoad.current=false;ordersRef.current=next;setOrders(next);setDemoMode(Boolean(d.demoMode));setError("");}catch(e){setError(e instanceof Error?e.message:"Siparişler yüklenemedi.");}finally{if(!silent)setLoading(false)}},[notify]);
  useEffect(()=>{if(user?.role!=="admin")return;void loadOrders();const timer=window.setInterval(()=>void loadOrders(true),8000);return()=>window.clearInterval(timer)},[user?.role,loadOrders]);
  const enable=async()=>{playSound();if(typeof Notification==="undefined")return void toast.error("Tarayıcı bildirim desteklemiyor.");const p=await Notification.requestPermission();setPermission(p);toast.success(p==="granted"?"Sipariş sesi ve bildirim açıldı.":"Panel açıkken sipariş sesi çalışacak.")};
  const updateStatus=async(id:number,status:OrderStatus)=>{setUpdatingId(id);try{const r=await fetch(`/api/admin/orders/${id}/status`,{method:"PATCH",headers:{"content-type":"application/json"},credentials:"include",body:JSON.stringify({status})});const d=await r.json();if(!r.ok)throw new Error(d.error);const next=ordersRef.current.map(o=>o.id===id?{...o,status}:o);ordersRef.current=next;setOrders(next);toast.success("Durum güncellendi.");}catch(e){setError(e instanceof Error?e.message:"Durum güncellenemedi.");}finally{setUpdatingId(null)}};
  const totals=useMemo(()=>({total:orders.length,production:orders.filter(o=>["confirmed","production","preparing"].includes(o.status)).length,shipping:orders.filter(o=>o.status==="shipping").length,revenue:orders.reduce((s,o)=>s+Number(o.totalPrice||0),0)}),[orders]);

  if(authLoading)return <div className="container py-16 text-center">Yükleniyor…</div>;
  if(!user||user.role!=="admin")return <div className="container py-16 text-center">Yetkisiz erişim</div>;
  return <div className="container py-8 space-y-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-medium text-primary">RGNFIX Yönetim</p><h1 className="text-3xl font-bold">Sipariş Yönetim Paneli</h1><p className="text-sm text-muted-foreground">Hoş geldiniz, {user.name||"Yönetici"}.</p></div><div className="flex flex-wrap gap-2"><Button variant={permission==="granted"?"secondary":"outline"} onClick={()=>void enable()}>{permission==="granted"?<BellRing className="mr-2 h-4 w-4"/>:<Bell className="mr-2 h-4 w-4"/>}Ses ve Bildirimi Aç</Button><Button asChild variant="outline"><Link href="/yonetici/fiyatlar">Fiyat Yönetimi</Link></Button><Button variant="outline" onClick={()=>void loadOrders()}><RefreshCw className="mr-2 h-4 w-4"/>Yenile</Button></div></div>
    {demoMode&&<div className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">Veritabanı bağlı değil.</div>}{error&&<div className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">{error}</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<ClipboardList/>} value={totals.total} label="Toplam sipariş"/><Stat icon={<PackageCheck/>} value={totals.production} label="Hazırlanan"/><Stat icon={<Truck/>} value={totals.shipping} label="Kargoda"/><Stat icon={<WalletCards/>} value={money(totals.revenue)} label="Toplam tutar"/></div>
    <Card className="overflow-hidden"><div className="border-b p-5 font-semibold">Siparişler</div>{loading?<div className="p-10 text-center">Yükleniyor…</div>:orders.length===0?<div className="p-10 text-center text-muted-foreground">Henüz sipariş yok.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[1320px] text-sm"><thead className="bg-muted/60 text-left"><tr>{["Sipariş","Müşteri","Ürün","Ölçü","Tutar","Tarih","Durum","İşlem"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{orders.map(o=><tr key={o.id} className="align-top"><td className="px-4 py-4 font-bold">#{o.orderNumber}</td><td className="px-4 py-4"><b>{o.customerName||"—"}</b><br/>{o.customerPhone}<p className="max-w-60 text-xs text-muted-foreground">{o.customerCity} {o.customerAddress}</p></td><td className="px-4 py-4"><b>{o.fabricName}</b><p className="text-xs text-muted-foreground">{o.fabricColor} / {o.profileColor}<br/>{o.mountType} / {o.caseType}</p></td><td className="px-4 py-4">{o.width} × {o.height} cm<br/><span className="text-xs">{o.quantity} adet</span></td><td className="px-4 py-4 font-bold">{money(o.totalPrice)}</td><td className="px-4 py-4">{date(o.createdAt)}</td><td className="px-4 py-4"><select value={o.status} onChange={e=>void updateStatus(o.id,e.target.value as OrderStatus)} disabled={updatingId===o.id} className="h-9 rounded-lg border bg-background px-2">{statusOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td className="px-4 py-4"><div className="flex gap-2"><Button asChild size="sm"><Link href={`/yonetici/siparis/${o.id}/duzenle`}><Pencil className="mr-2 h-4 w-4"/>Tam Düzenle</Link></Button><Button size="sm" variant="outline" onClick={()=>printOrder(o)}><Printer className="mr-2 h-4 w-4"/>A5</Button></div></td></tr>)}</tbody></table></div>}</Card>
  </div>;
}
function Stat({icon,value,label}:{icon:React.ReactNode;value:React.ReactNode;label:string}){return <Card className="p-5"><div className="h-5 w-5 text-primary">{icon}</div><p className="mt-4 text-2xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></Card>}
